
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
