###

POST http://localhost:3000/users
content-type: application/json

{
    "name": "leticia",
    "password": "teste",
    "email": "teste1@teste.com"
}

###

POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "teste1@teste.com",
    "password": "teste"
}